import { Language } from './types';

interface Strings {
  [key: string]: { [key: string]: string };
}

export const strings: Strings = {
  ar: {
    appName: 'تونسي',
    home: 'الرئيسية',
    profile: 'الملف الشخصي',
    messages: 'الرسائل',
    marketplace: 'السوق',
    videoCalls: 'مكالمات الفيديو',
    settings: 'الإعدادات',
    account: 'الحساب',
    notifications: 'الإشعارات',
    privacy: 'الخصوصية',
    appearance: 'المظهر',
    changeLanguage: 'تغيير اللغة',
    logout: 'تسجيل الخروج',
    editPost: 'تعديل المنشور',
    cancel: 'إلغاء',
    save: 'حفظ',
    likesCount: 'إعجاب',
    commentsCount: 'تعليق',
    like: 'أعجبني',
    comment: 'تعليق',
    share: 'مشاركة',
    createPostTitle: 'إنشاء منشور جديد',
    whatsHappening: 'بماذا تفكر؟',
    photo: 'صورة',
    video: 'فيديو',
    post: 'نشر',
    posts: 'منشورات',
    followers: 'متابعون',
    following: 'يتابع',
    editProfile: 'تعديل الملف الشخصي',
    photos: 'الصور',
    videos: 'الفيديوهات',
    search: 'بحث',
    typeMessage: 'اكتب رسالة...',
    selectConversation: 'حدد محادثة لبدء الدردشة',
    searchMarketplace: 'البحث في السوق...',
    activeVideoCall: 'مكالمة فيديو نشطة',
    callEnded: 'انتهت المكالمة',
    sendAttachment: 'إرسال مرفق',
    image: 'صورة',
    file: 'ملف',
    loginTitle: 'مرحباً بعودتك إلى تونسي',
    loginSubtitle: 'التطبيق الاجتماعي الأول في تونس',
    emailLabel: 'البريد الإلكتروني',
    passwordLabel: 'كلمة المرور',
    loginButton: 'تسجيل الدخول',
    noAccount: 'ليس لديك حساب؟',
    signUp: 'إنشاء حساب',
    signUpTitle: 'انضم إلى تونسي اليوم',
    nameLabel: 'الاسم',
    confirmPasswordLabel: 'تأكيد كلمة المرور',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    login: 'تسجيل الدخول',
    contactSupport: 'للمساعدة، تواصل معنا:',
    emailContact: 'البريد الإلكتروني:',
    phoneContact: 'الهاتف:',
    privacyTitle: 'سياسة الخصوصية',
    privacyIntro: 'خصوصيتك تهمنا. توضح هذه السياسة كيفية جمعنا لمعلوماتك الشخصية واستخدامها وحمايتها.',
    privacyPoint1: 'جمع البيانات: نجمع البيانات الضرورية فقط لتقديم خدماتنا، مثل بريدك الإلكتروني لإنشاء الحساب.',
    privacyPoint2: 'موافقة المستخدم: نطلب دائمًا موافقتك قبل جمع معلوماتك الشخصية.',
    privacyPoint3: 'الغرض من البيانات: تُستخدم بياناتك فقط لتحسين تجربتك في التطبيق ولن يتم بيعها لأطراف ثالثة.',
    privacyPoint4: 'حقوق المستخدم: لك الحق في الوصول إلى بياناتك الشخصية أو تصحيحها أو حذفها في أي وقت.',
    privacyPoint5: 'أمان البيانات: نستخدم تشفيرًا وإجراءات أمنية متوافقة مع معايير الصناعة لحماية معلوماتك.',
    privacyPoint6: 'الاحتفاظ بالبيانات: نحتفظ ببياناتك فقط طالما كان ذلك ضروريًا لتقديم الخدمات أو كما يقتضي القانون.',
    privacyPoint7: 'المشاركة مع أطراف ثالثة: لا نشارك بياناتك الشخصية مع أطراف ثالثة دون موافقتك الصريحة، إلا كما يقتضي القانون.',
    privacyPoint8: 'ملفات تعريف الارتباط والتتبع: نستخدم الحد الأدنى من ملفات تعريف الارتباط للوظائف الأساسية. لا نستخدم أدوات تتبع من أطراف ثالثة للإعلانات.',
    privacyPoint9: 'خصوصية الأطفال: خدمتنا غير موجهة للأطفال دون سن 13 عامًا، ولا نجمع بياناتهم عن قصد.',
    privacyPoint10: 'تحديثات السياسة: سنخطرك بأي تغييرات مهمة تطرأ على سياسة الخصوصية هذه.',
    termsTitle: 'شروط الخدمة',
    termsIntro: 'مرحبًا بك في تونسي! باستخدام تطبيقنا، فإنك توافق على هذه الشروط. يرجى قراءتها بعناية.',
    termsPoint1: 'قبول الشروط: من خلال الوصول إلى خدمتنا أو استخدامها، فإنك توافق على الالتزام بهذه الشروط.',
    termsPoint2: 'استخدام الخدمة: يجب عليك اتباع أي سياسات متاحة لك داخل الخدمة. لا تسيء استخدام خدماتنا.',
    termsPoint3: 'حسابك: أنت مسؤول عن الحفاظ على سرية حسابك وكلمة مرورك.',
    termsPoint4: 'المحتوى الخاص بك: أنت تحتفظ بملكية حقوق الملكية الفكرية التي تمتلكها في هذا المحتوى.',
    termsPoint5: 'إنهاء الخدمة: يجوز لنا إنهاء أو تعليق وصولك إلى خدمتنا فورًا، دون إشعار مسبق أو مسؤولية، لأي سبب من الأسباب.',
    termsPoint6: 'إخلاء المسؤولية عن الضمانات: يتم توفير خدمتنا "كما هي". لا نقدم أي ضمانات صريحة أو ضمنية.',
    termsPoint7: 'حدود المسؤولية: لن نكون مسؤولين عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو عقابية.',
    termsPoint8: 'القانون الحاكم: تخضع هذه الشروط وتُفسر وفقًا لقوانين تونس.',
    termsPoint9: 'التغييرات على الشروط: نحتفظ بالحق، وفقًا لتقديرنا الخاص، في تعديل أو استبدال هذه الشروط في أي وقت.',
    termsPoint10: 'اتصل بنا: إذا كانت لديك أي أسئلة حول هذه الشروط، فيرجى الاتصال بنا.',
    cookieConsent: 'نحن نستخدم ملفات تعريف الارتباط لضمان حصولك على أفضل تجربة على تطبيقنا.',
    accept: 'قبول',
    decline: 'رفض',
    agreeToTerms: 'أوافق على',
    and: 'و',
    termsOfService: 'شروط الخدمة',
  },
  fr: {
    appName: 'Tounsi',
    home: 'Accueil',
    profile: 'Profil',
    messages: 'Messages',
    marketplace: 'Marché',
    videoCalls: 'Appels Vidéo',
    settings: 'Paramètres',
    account: 'Compte',
    notifications: 'Notifications',
    privacy: 'Confidentialité',
    appearance: 'Apparence',
    changeLanguage: 'Changer de langue',
    logout: 'Déconnexion',
    editPost: 'Modifier la publication',
    cancel: 'Annuler',
    save: 'Enregistrer',
    likesCount: 'J\'aime',
    commentsCount: 'Commentaires',
    like: 'J\'aime',
    comment: 'Commenter',
    share: 'Partager',
    createPostTitle: 'Créer une nouvelle publication',
    whatsHappening: 'À quoi pensez-vous ?',
    photo: 'Photo',
    video: 'Vidéo',
    post: 'Publier',
    posts: 'Publications',
    followers: 'Abonnés',
    following: 'Abonnements',
    editProfile: 'Modifier le profil',
    photos: 'Photos',
    videos: 'Vidéos',
    search: 'Rechercher',
    typeMessage: 'Écrire un message...',
    selectConversation: 'Sélectionnez une conversation pour commencer',
    searchMarketplace: 'Rechercher sur le marché...',
    activeVideoCall: 'Appel vidéo en cours',
    callEnded: 'Appel terminé',
    sendAttachment: 'Envoyer une pièce jointe',
    image: 'Image',
    file: 'Fichier',
    loginTitle: 'Bienvenue sur Tounsi',
    loginSubtitle: 'La première application sociale en Tunisie',
    emailLabel: 'Email',
    passwordLabel: 'Mot de passe',
    loginButton: 'Se connecter',
    noAccount: 'Pas de compte ?',
    signUp: 'S\'inscrire',
    signUpTitle: 'Rejoignez Tounsi aujourd\'hui',
    nameLabel: 'Nom',
    confirmPasswordLabel: 'Confirmer le mot de passe',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    login: 'Se connecter',
    contactSupport: 'Pour le support, contactez-nous :',
    emailContact: 'Email :',
    phoneContact: 'Téléphone :',
    privacyTitle: 'Politique de Confidentialité',
    privacyIntro: 'Votre vie privée est importante pour nous. Cette politique explique comment nous collectons, utilisons et protégeons vos informations personnelles.',
    privacyPoint1: 'Collecte de données : Nous collectons uniquement les données nécessaires pour fournir nos services, comme votre email pour la création de compte.',
    privacyPoint2: 'Consentement de l\'utilisateur : Nous demandons toujours votre consentement avant de collecter des informations personnelles.',
    privacyPoint3: 'Finalité des données : Vos données sont utilisées uniquement pour améliorer votre expérience sur l\'application et ne seront pas vendues à des tiers.',
    privacyPoint4: 'Droits de l\'utilisateur : Vous avez le droit d\'accéder, de corriger ou de supprimer vos données personnelles à tout moment.',
    privacyPoint5: 'Sécurité des données : Nous utilisons des mesures de chiffrement et de sécurité conformes aux normes de l\'industrie pour protéger vos informations.',
    privacyPoint6: 'Conservation des données : Nous ne conservons vos données que le temps nécessaire pour fournir les services ou comme l\'exige la loi.',
    privacyPoint7: 'Partage avec des tiers : Nous ne partageons pas vos données personnelles avec des tiers sans votre consentement explicite, sauf si la loi l\'exige.',
    privacyPoint8: 'Cookies & Suivi : Nous utilisons un minimum de cookies pour les fonctionnalités essentielles. Nous n\'utilisons pas de traceurs tiers pour la publicité.',
    privacyPoint9: 'Confidentialité des enfants : Notre service n\'est pas destiné aux enfants de moins de 13 ans, et nous ne collectons pas sciemment leurs données.',
    privacyPoint10: 'Mises à jour de la politique : Nous vous informerons de toute modification importante de cette politique de confidentialité.',
    termsTitle: 'Conditions d\'Utilisation',
    termsIntro: 'Bienvenue sur Tounsi ! En utilisant notre application, vous acceptez ces conditions. Veuillez les lire attentivement.',
    termsPoint1: 'Acceptation des conditions : En accédant ou en utilisant notre service, vous acceptez d\'être lié par ces conditions.',
    termsPoint2: 'Utilisation du service : Vous devez suivre toutes les politiques mises à votre disposition dans le service. N\'utilisez pas nos services de manière abusive.',
    termsPoint3: 'Votre compte : Vous êtes responsable de la protection de votre compte et de votre mot de passe.',
    termsPoint4: 'Votre contenu : Vous conservez la propriété de tous les droits de propriété intellectuelle que vous détenez sur ce contenu.',
    termsPoint5: 'Résiliation : Nous pouvons résilier ou suspendre l\'accès à notre service immédiatement, sans préavis ni responsabilité, pour quelque raison que ce soit.',
    termsPoint6: 'Exclusion de garanties : Notre service est fourni "TEL QUEL". Nous n\'offrons aucune garantie, expresse ou implicite.',
    termsPoint7: 'Limitation de responsabilité : Nous ne serons pas responsables des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs.',
    termsPoint8: 'Droit applicable : Ces conditions seront régies et interprétées conformément aux lois de la Tunisie.',
    termsPoint9: 'Modifications des conditions : Nous nous réservons le droit, à notre seule discrétion, de modifier ou de remplacer ces conditions à tout moment.',
    termsPoint10: 'Contactez-nous : Si vous avez des questions sur ces conditions, veuillez nous contacter.',
    cookieConsent: 'Nous utilisons des cookies pour vous garantir la meilleure expérience sur notre application.',
    accept: 'Accepter',
    decline: 'Refuser',
    agreeToTerms: 'J\'accepte les',
    and: 'et la',
    termsOfService: 'Conditions d\'Utilisation',
  },
};
